apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc 
spec: 
  storageClassName: manual 
  accessModes: 
    # the storage (say our node) have to have
    # storage option that provides following permissions
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 0.5Gi
