apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc 
spec: 
  accessModes: 
    # the storage (say our node) have to have
    # storage option that provides following permissions
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  hostPath: 
    path: "E:\\Linux\\mongo"
